[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[server]
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
